remote_theme: chrisrhymes/bulma-clean-theme
title: Frictionless Enterprise
author: Phil Wainewright
email: pw@pcxvs.com
description: A framework for thinking about digital transformation developed by trusted business writer and cloud computing expert Phil Wainewright
favicon: favicon.png

# Pagination settings
paginate: 5
paginate_path: "blog/page:num"

# social links
twitter_username: philww # DO NOT include the @ character, or else the build will fail!
github_username:  philww241 # DO NOT include the @ character, or else the build will fail!

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true # set to false to remove sidebar excerpts 

