remote_theme: chrisrhymes/bulma-clean-theme
title: My first github blog
author: Phil Wainewright
email: pw@pcxvs.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first attempt at creating a blog in github and
  publishing it using Jekyll. Here you will find information
  about how I did this and what I plan to do next.

# social links
twitter_username: philww # DO NOT include the @ character, or else the build will fail!
github_username:  philww241 # DO NOT include the @ character, or else the build will fail!

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true # set to false to remove sidebar excerpts 

